services:
  thinkdepthai_deepresearch:
    image: thinkdepthai_deepresearch
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    ports:
      - 127.0.0.1:8501:8501
